"""empty message

Revision ID: 051cea3dbbef
Revises: 5cb01d94cbd2
Create Date: 2022-09-12 12:06:05.423833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '051cea3dbbef'
down_revision = '5cb01d94cbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'tag', ['tag_id'], ['id'])
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
