"""initial migration

Revision ID: 59a61d3633a3
Revises: 
Create Date: 2022-09-07 13:51:01.303299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59a61d3633a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.Column('razao_social', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nome_fantasia', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('logradouro', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=True),
    sa.Column('municipio', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=True),
    sa.Column('estado', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=True),
    sa.Column('pais', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('logradouro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('municipio', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pais', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('perfil', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ativo', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('empresa', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
