"""empty message

Revision ID: 9a7bb28d737c
Revises: 051cea3dbbef
Create Date: 2022-09-12 14:05:06.453528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a7bb28d737c'
down_revision = '051cea3dbbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comment', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'tag', ['tag_id'], ['id'])
    op.alter_column('tag', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index('title', table_name='tag')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index('title', 'tag', ['title'], unique=False)
    op.alter_column('tag', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('comment', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
